name: FTP Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Verify Vendor Directory
        run: ls -la ./vendor

      - name: FTP Deploy Forked
        uses: snorux/FTP-Deploy-Action@1.3.2
        with:
          server: ftpupload.net
          username: if0_37694479
          password: qLQphFCzJXW
          protocol: ftps
          port: 21
          local-dir: ./ # Ensure everything, including vendor, is uploaded
          server-dir: /htdocs/getUp_Assignment/
